### PR TITLE
Fix UtilsCubemap compilation error in Ubuntu 22.04

### PR DESCRIPTION
**Pull request by ghidosoft**
I just added a single missing `#include <cstdio>` for a `printf` in `shared/UtilsCubemap.cpp`: it now correctly builds on Ubuntu 22.04.

### CODE REVIEW

**Comment by corporateshark** [comment]
@ghidosoft Thank you!
